services:

  subscription-solver-web: 
    container_name: subscription-solver-web
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '5173:5173'
