services:
  development:
    container_name: development
    build:
      context: .
      dockerfile: Dockerfile
      target: development-stage
    volumes:
      - '.:/usr/src/app'
      - './node_modules:/usr/src/app/node_modules'
    ports:
      - '5173:5173'
    profiles: [development]

  production:
    container_name: production
    build:
      context: .
      dockerfile: Dockerfile
      target: production-stage
    ports:
      - '8000:80'
    profiles: [production]
